// ============================================================================
// ASTITVA 2K26 - Events & Categories Seed (Full Festival Catalog)
// Path: scripts/seed-astitva-events.ts
// ============================================================================

import { PrismaClient, CategoryType, EventType, EventStatus } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding complete official festival events into Supabase PostgreSQL...");

  // 1. Categories
  const categories = [
    {
      id: "cat-sports",
      slug: "sports",
      name: "Sports Championship",
      type: CategoryType.SPORTS,
      description: "Flagship inter-branch athletic competitions and tournament leagues.",
      icon: "Trophy",
      order: 1,
      isActive: true,
    },
    {
      id: "cat-cultural",
      slug: "cultural",
      name: "Cultural & Arts",
      type: CategoryType.CULTURAL,
      description: "Celebrating music, dance, theater, fashion, and performing arts.",
      icon: "Palette",
      order: 2,
      isActive: true,
    },
    {
      id: "cat-gaming",
      slug: "gaming",
      name: "Esports & Gaming",
      type: CategoryType.GAMING,
      description: "High-octane competitive mobile and PC gaming battle arenas.",
      icon: "Gamepad2",
      order: 3,
      isActive: true,
    },
    {
      id: "cat-literary",
      slug: "literary",
      name: "Literary Arena",
      type: CategoryType.LITERARY,
      description: "Intellectual discourse, debates, poetry, and quizzes.",
      icon: "BookOpen",
      order: 4,
      isActive: true,
    },
  ];

  for (const cat of categories) {
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: cat,
      create: cat,
    });
  }
  console.log("Categories upserted successfully.");

  // 2. Events List (19 total events across 5 days)
  const events = [
    // ------------------------------------------------------------------------
    // SPORTS EVENTS
    // ------------------------------------------------------------------------
    {
      id: "evt-cricket",
      slug: "cricket-championship",
      title: "Cricket Championship (T20)",
      subtitle: "11-a-side Inter-Branch Tournament",
      description: "The premier inter-branch cricket tournament of LNJPIT Chapra. Showcase your team's batting depth, fast bowling attack, and strategic fielding on the main campus ground.",
      rules: "1. 11 players per playing side with up to 4 substitutes (Total roster: 11-15).\n2. Standard T20 limited-overs rules apply.\n3. Matches will be played with standard red/white leather/heavy tennis cricket balls.\n4. All players must wear proper sports kits and carry their LNJPIT ID & ASTITVA QR Pass.\n5. Decision of the field umpires is final and binding.",
      categoryId: "cat-sports",
      venue: "Main Sports Ground, LNJPIT Campus",
      eventType: EventType.TEAM,
      minTeamSize: 11,
      maxTeamSize: 15,
      registrationFee: 0,
      maxRegistrations: 16,
      prizePool: 0,
      firstPrize: "Winner Trophy + Gold Medals + Certificate of Excellence",
      secondPrize: "Runner-Up Trophy + Silver Medals + Certificate of Merit",
      thirdPrize: "Bronze Medals + Certificate of Commendation",
      scheduleStart: new Date("2026-09-04T09:00:00+05:30"),
      scheduleEnd: new Date("2026-09-04T17:00:00+05:30"),
      dayNumber: 1,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: true,
      coordinatorName: "Sports Committee",
      coordinatorEmail: "sports@lnjpit.ac.in",
    },
    {
      id: "evt-fun-cricket",
      slug: "fun-cricket",
      title: "Fun Cricket (Box Cricket)",
      subtitle: "6-a-side High-Adrenaline Net Cricket",
      description: "Fast-paced, rapid box cricket inside the arena net grounds. Direct-hit boundaries, single-run zones, fast overs, and intense excitement for every student!",
      rules: "1. 6 players on the field + up to 2 substitutes (Team size: 6-8).\n2. 6-over rapid match with strict over-time restrictions.\n3. Direct wall boundary rules and zone-scoring system will be explained before toss.\n4. One-bounce catches off designated side nets are OUT.\n5. Underarm / swift chucking restrictions apply as per box cricket regulations.",
      categoryId: "cat-sports",
      venue: "Inner Sports Arena / Net Ground, LNJPIT",
      eventType: EventType.TEAM,
      minTeamSize: 6,
      maxTeamSize: 8,
      registrationFee: 0,
      maxRegistrations: 32,
      prizePool: 0,
      firstPrize: "Box Cricket Champions Trophy + Medals + Certificates",
      secondPrize: "Runner-Up Trophy + Silver Medals + Certificates",
      thirdPrize: "Bronze Medals + Certificates",
      scheduleStart: new Date("2026-09-05T10:00:00+05:30"),
      scheduleEnd: new Date("2026-09-05T16:00:00+05:30"),
      dayNumber: 2,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: true,
      coordinatorName: "Fun Events Wing",
      coordinatorEmail: "sports@lnjpit.ac.in",
    },
    {
      id: "evt-badminton-singles",
      slug: "badminton-singles",
      title: "Badminton Singles (Men & Women)",
      subtitle: "Solo Badminton Championship",
      description: "Individual badminton tournament testing stamina, lightning-quick reflexes, smashes, and cross-court drops on the indoor wooden courts.",
      rules: "1. Individual 1v1 knockout tournament format.\n2. BWF standard scoring system: Best of 3 sets, 21 points each.\n3. Non-marking indoor court shoes are mandatory.\n4. Standard Yonex feather/nylon shuttlecocks provided.\n5. Warm-up time limited to 2 minutes prior to each fixture.",
      categoryId: "cat-sports",
      venue: "Indoor Badminton Court, LNJPIT Sports Complex",
      eventType: EventType.INDIVIDUAL,
      minTeamSize: 1,
      maxTeamSize: 1,
      registrationFee: 0,
      maxRegistrations: 64,
      prizePool: 0,
      firstPrize: "Singles Champion Trophy + Gold Medal + Certificate of Excellence",
      secondPrize: "Runner-Up Trophy + Silver Medal + Certificate of Merit",
      thirdPrize: "Bronze Medal + Certificate of Commendation",
      scheduleStart: new Date("2026-09-05T09:30:00+05:30"),
      scheduleEnd: new Date("2026-09-05T17:30:00+05:30"),
      dayNumber: 2,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: true,
      coordinatorName: "Badminton Club LNJPIT",
      coordinatorEmail: "sports@lnjpit.ac.in",
    },
    {
      id: "evt-badminton-doubles",
      slug: "badminton-doubles",
      title: "Badminton Doubles",
      subtitle: "2-Player Team Badminton Clash",
      description: "Pair up with your partner for dynamic doubles badminton action. Coordinated court coverage, steep attacks, and fast-paced rallies.",
      rules: "1. Team size: Exactly 2 players per pair.\n2. Standard BWF doubles court boundaries and service rotation rules apply.\n3. Best of 3 sets (21 points) in preliminary rounds and finals.\n4. Both partners must wear non-marking shoes.\n5. Substitutions after tournament bracket release are not permitted.",
      categoryId: "cat-sports",
      venue: "Indoor Badminton Court, LNJPIT Sports Complex",
      eventType: EventType.TEAM,
      minTeamSize: 2,
      maxTeamSize: 2,
      registrationFee: 0,
      maxRegistrations: 32,
      prizePool: 0,
      firstPrize: "Doubles Champions Trophy + Gold Medals + Certificates",
      secondPrize: "Runner-Up Trophy + Silver Medals + Certificates",
      thirdPrize: "Bronze Medals + Certificates",
      scheduleStart: new Date("2026-09-06T09:30:00+05:30"),
      scheduleEnd: new Date("2026-09-06T17:30:00+05:30"),
      dayNumber: 3,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: true,
      coordinatorName: "Badminton Club LNJPIT",
      coordinatorEmail: "sports@lnjpit.ac.in",
    },
    {
      id: "evt-table-tennis",
      slug: "table-tennis",
      title: "Table Tennis Tournament (Singles & Doubles)",
      subtitle: "Fast-Paced Ping Pong Championship",
      description: "High-speed spins, sharp chops, and lightning returns on official STIGA table tennis boards in the Student Activity Center.",
      rules: "1. Individual / Pair participation (Size: 1 to 2 players).\n2. ITTF 11-point game rules with alternate 2 serves.\n3. Best of 3 sets in qualifiers; Best of 5 sets in Semi-finals and Finals.\n4. Standard 40mm+ three-star celluloid/plastic balls will be used.\n5. Players may use their own ITTF-approved rubber racquets or provided tournament bats.",
      categoryId: "cat-sports",
      venue: "Student Activity Center (SAC) TT Hall, LNJPIT",
      eventType: EventType.INDIVIDUAL,
      minTeamSize: 1,
      maxTeamSize: 2,
      registrationFee: 0,
      maxRegistrations: 64,
      prizePool: 0,
      firstPrize: "Table Tennis Trophy + Gold Medal + Certificate of Excellence",
      secondPrize: "Runner-Up Trophy + Silver Medal + Certificate of Merit",
      thirdPrize: "Bronze Medal + Certificate of Commendation",
      scheduleStart: new Date("2026-09-06T10:00:00+05:30"),
      scheduleEnd: new Date("2026-09-06T18:00:00+05:30"),
      dayNumber: 3,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: true,
      coordinatorName: "Table Tennis Club",
      coordinatorEmail: "sports@lnjpit.ac.in",
    },
    {
      id: "evt-football",
      slug: "football-tournament",
      title: "Football Tournament",
      subtitle: "Inter-Branch 7-a-Side Cup",
      description: "The annual inter-branch football tournament under the campus floodlights. Precision passing, dynamic counter-attacks, and world-class saves.",
      rules: "1. 7 players on field + up to 4 rolling substitutes (Team size: 7-11).\n2. 20-minute halves with a 5-minute break.\n3. Shin guards are strongly advised.\n4. Direct red cards lead to suspension for the following fixture.",
      categoryId: "cat-sports",
      venue: "Football Ground, LNJPIT Campus",
      eventType: EventType.TEAM,
      minTeamSize: 7,
      maxTeamSize: 11,
      registrationFee: 0,
      maxRegistrations: 16,
      prizePool: 0,
      firstPrize: "Football Champions Trophy + Gold Medals + Certificates",
      secondPrize: "Runner-Up Trophy + Silver Medals + Certificates",
      thirdPrize: "Bronze Medals + Certificates",
      scheduleStart: new Date("2026-09-04T14:00:00+05:30"),
      scheduleEnd: new Date("2026-09-04T19:00:00+05:30"),
      dayNumber: 1,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: false,
      coordinatorName: "Football Club",
      coordinatorEmail: "sports@lnjpit.ac.in",
    },
    {
      id: "evt-volleyball",
      slug: "volleyball-spikers-cup",
      title: "Volleyball Spikers Cup",
      subtitle: "Inter-Branch Volleyball League",
      description: "Electrifying volleyball matches featuring powerful jumps, quick sets, and solid blocks.",
      rules: "1. 6 players on court + 2 substitutes (Team size: 6-8).\n2. Best of 3 sets (25-25-15 points).\n3. FIVB standard net height and rotation rules apply.",
      categoryId: "cat-sports",
      venue: "Outdoor Volleyball Court, LNJPIT",
      eventType: EventType.TEAM,
      minTeamSize: 6,
      maxTeamSize: 8,
      registrationFee: 0,
      maxRegistrations: 16,
      prizePool: 0,
      firstPrize: "Volleyball Spikers Trophy + Gold Medals + Certificates",
      secondPrize: "Runner-Up Trophy + Silver Medals + Certificates",
      thirdPrize: "Bronze Medals + Certificates",
      scheduleStart: new Date("2026-09-05T14:00:00+05:30"),
      scheduleEnd: new Date("2026-09-05T18:00:00+05:30"),
      dayNumber: 2,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: false,
      coordinatorName: "Volleyball Club",
      coordinatorEmail: "sports@lnjpit.ac.in",
    },
    {
      id: "evt-chess",
      slug: "grandmaster-chess-blitz",
      title: "Grandmaster Chess Blitz",
      subtitle: "Tactical Clock Blitz Tournament",
      description: "10-minute clock rapid chess tournament testing opening theory, tactical awareness, and endgame precision.",
      rules: "1. Individual participation.\n2. FIDE Rapid & Blitz time control: 10 minutes + 2-second increment.\n3. Swiss-system 5 preliminary rounds, top 4 advance to knockout semifinals.",
      categoryId: "cat-sports",
      venue: "Auditorium Seminar Hall A, LNJPIT",
      eventType: EventType.INDIVIDUAL,
      minTeamSize: 1,
      maxTeamSize: 1,
      registrationFee: 0,
      maxRegistrations: 64,
      prizePool: 0,
      firstPrize: "Grandmaster Trophy + Gold Medal + Certificate of Excellence",
      secondPrize: "Runner-Up Trophy + Silver Medal + Certificate of Merit",
      thirdPrize: "Bronze Medal + Certificate of Commendation",
      scheduleStart: new Date("2026-09-06T11:00:00+05:30"),
      scheduleEnd: new Date("2026-09-06T16:00:00+05:30"),
      dayNumber: 3,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: false,
      coordinatorName: "Chess Club LNJPIT",
      coordinatorEmail: "sports@lnjpit.ac.in",
    },

    // ------------------------------------------------------------------------
    // CULTURAL EVENTS & GRAND FINALE (Day 4 & Day 5)
    // ------------------------------------------------------------------------
    {
      id: "evt-singing",
      slug: "voice-of-astitva",
      title: "Voice of Astitva (Singing)",
      subtitle: "Solo & Duet Musical Showcase",
      description: "A melody-filled musical battle showcasing classical ragas, soul-stirring ghazals, Bollywood hits, and Western acoustic numbers.",
      rules: "1. Time limit: 4 minutes per participant/pair.\n2. Karaoke tracks or one acoustic accompanist allowed.\n3. Judging on sur, taal, voice texture, and overall presentation.",
      categoryId: "cat-cultural",
      venue: "Main Auditorium, LNJPIT",
      eventType: EventType.INDIVIDUAL,
      minTeamSize: 1,
      maxTeamSize: 2,
      registrationFee: 0,
      maxRegistrations: 50,
      prizePool: 0,
      firstPrize: "Voice of Astitva Trophy + Gold Medal + Certificate",
      secondPrize: "Runner-Up Trophy + Silver Medal + Certificate",
      thirdPrize: "Bronze Medal + Certificate",
      scheduleStart: new Date("2026-09-06T16:00:00+05:30"),
      scheduleEnd: new Date("2026-09-06T20:00:00+05:30"),
      dayNumber: 3,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: false,
      coordinatorName: "Music Club LNJPIT",
      coordinatorEmail: "cultural@lnjpit.ac.in",
    },
    {
      id: "evt-comedy",
      slug: "standup-comedy",
      title: "Stand-Up Comedy Spotlight",
      subtitle: "Live Comedy Open Mic",
      description: "Original jokes, punchlines, campus humor, and satirical takes on stage.",
      rules: "1. 5 minutes stage time.\n2. Original content only; direct plagiarized sets will be disqualified.\n3. Hate speech and discriminatory remarks are strictly prohibited.",
      categoryId: "cat-cultural",
      venue: "Main Auditorium, LNJPIT",
      eventType: EventType.INDIVIDUAL,
      minTeamSize: 1,
      maxTeamSize: 1,
      registrationFee: 0,
      maxRegistrations: 30,
      prizePool: 0,
      firstPrize: "Comedy King/Queen Trophy + Gold Medal + Certificate",
      secondPrize: "Runner-Up Trophy + Silver Medal + Certificate",
      thirdPrize: "Bronze Medal + Certificate",
      scheduleStart: new Date("2026-09-07T14:00:00+05:30"),
      scheduleEnd: new Date("2026-09-07T16:30:00+05:30"),
      dayNumber: 4,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: false,
      coordinatorName: "Drama & Comedy Society",
      coordinatorEmail: "cultural@lnjpit.ac.in",
    },
    {
      id: "evt-rampwalk",
      slug: "fashion-odyssey",
      title: "Fashion Odyssey (Ramp Walk)",
      subtitle: "Inter-Branch Runway Gala",
      description: "The premier runway fashion show celebrating theme elegance, cultural attires, and stage charisma.",
      rules: "1. Team size: 6 to 12 models.\n2. 8 to 10 minutes runway performance per branch.\n3. Theme coherence, styling, stage formation, and attitude will be evaluated.",
      categoryId: "cat-cultural",
      venue: "Main Stage (OAT), LNJPIT",
      eventType: EventType.TEAM,
      minTeamSize: 6,
      maxTeamSize: 12,
      registrationFee: 0,
      maxRegistrations: 10,
      prizePool: 0,
      firstPrize: "Fashion Odyssey Champions Trophy + Medals + Certificates",
      secondPrize: "Runner-Up Trophy + Silver Medals + Certificates",
      thirdPrize: "Bronze Medals + Certificates",
      scheduleStart: new Date("2026-09-07T17:30:00+05:30"),
      scheduleEnd: new Date("2026-09-07T21:30:00+05:30"),
      dayNumber: 4,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: true,
      coordinatorName: "Fashion Wing LNJPIT",
      coordinatorEmail: "cultural@lnjpit.ac.in",
    },
    // DAY 5: MAJOR DANCE EVENT
    {
      id: "evt-dance",
      slug: "dance-battle",
      title: "Grand Finale Mega Dance Battle (Solo & Group)",
      subtitle: "Major Inter-Branch Dance Championship",
      description: "The flagship, high-energy major dance competition of ASTITVA 2K26 held on the grand finale day. Featuring solo performances, synchronized branch crews, Bollywood power-moves, and explosive hip-hop routines on the main Open Air Theater stage!",
      rules: "1. Solo (3-5 minutes) or Group Crew (3-12 members, 6-10 minutes).\n2. Music tracks must be submitted in high quality to the cultural desk by 11:00 AM on Day 5.\n3. Judging criteria: Choreography, stage formation, expression, synchronicity, and costume theme.\n4. Fire, water, or hazardous props are strictly prohibited.",
      categoryId: "cat-cultural",
      venue: "Main Open Air Theater (OAT) Stage, LNJPIT",
      eventType: EventType.TEAM,
      minTeamSize: 1,
      maxTeamSize: 12,
      registrationFee: 0,
      maxRegistrations: 40,
      prizePool: 0,
      firstPrize: "Grand Natraj Dance Champions Trophy + Gold Medals + Certificate of Excellence",
      secondPrize: "Runner-Up Trophy + Silver Medals + Certificate of Merit",
      thirdPrize: "Bronze Medals + Certificate of Commendation",
      scheduleStart: new Date("2026-09-08T14:00:00+05:30"),
      scheduleEnd: new Date("2026-09-08T17:30:00+05:30"),
      dayNumber: 5,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: true,
      coordinatorName: "Cultural & Dance Club LNJPIT",
      coordinatorEmail: "cultural@lnjpit.ac.in",
    },
    // DAY 5: GRAND PRIZE DISTRIBUTION & VALEDICTORY
    {
      id: "evt-prize-distribution",
      slug: "grand-prize-distribution-valedictory",
      title: "Grand Prize Distribution & Valedictory Gala",
      subtitle: "Honoring Champions & Overall Championship Trophy",
      description: "The official closing ceremony and grand award felicitation of ASTITVA 2K26. Presentation of tournament championship cups, gold/silver medals, merit certificates, and the prestigious ASTITVA 2K26 Overall Branch Championship Trophy by the Principal, Deans, and Honored Chief Guests.",
      rules: "1. All podium winners, captains, and runners-up must assemble in the reserved seating section by 17:15.\n2. Valid ASTITVA QR Pass is mandatory for stage entry.\n3. Official department points will be tallied live on the Big Screen before awarding the Overall Championship Trophy.\n4. Certificates of Commendation and Volunteer Badges will be awarded.",
      categoryId: "cat-cultural",
      venue: "Main Auditorium & Central OAT Arena, LNJPIT",
      eventType: EventType.INDIVIDUAL,
      minTeamSize: 1,
      maxTeamSize: 50,
      registrationFee: 0,
      maxRegistrations: 500,
      prizePool: 0,
      firstPrize: "Overall Branch Champion Mega Trophy + Department Honors",
      secondPrize: "Branch Runner-Up Trophy",
      thirdPrize: "Fair Play & Best Participation Trophy",
      scheduleStart: new Date("2026-09-08T17:30:00+05:30"),
      scheduleEnd: new Date("2026-09-08T19:30:00+05:30"),
      dayNumber: 5,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: true,
      coordinatorName: "Organizing Committee & Faculty Coordinators",
      coordinatorEmail: "astitva2026@lnjpit.ac.in",
    },
    // DAY 5: CELEBRITY DJ NIGHT & NIGHT PARTY
    {
      id: "evt-night-party",
      slug: "celebrity-dj-star-night-party",
      title: "Celebrity DJ Night & Star Night Party",
      subtitle: "The Ultimate Festival Finale Night Party & EDM Blast",
      description: "The grand festival finale! An electrifying high-voltage night featuring celebrity DJ performances, state-of-the-art concert lighting, laser visual effects, Bollywood chartbusters, and EDM bass drops under the night sky to conclude ASTITVA 2K26 with boundless energy!",
      rules: "1. Entry strictly restricted to verified LNJPIT students, faculty, and authorized fest delegates carrying valid ASTITVA Digital QR Passes.\n2. College ID Card + QR Pass check-in mandatory at the Arena Security Gate.\n3. Campus security and discipline protocols apply. Strict zero-tolerance policy against misconduct.\n4. Glass bottles, outside drinks, or unauthorized items are prohibited.\n5. Keep your QR Badge ready on your phone for fast gate verification.",
      categoryId: "cat-cultural",
      venue: "Main Festival Ground / Central Arena, LNJPIT Campus",
      eventType: EventType.INDIVIDUAL,
      minTeamSize: 1,
      maxTeamSize: 1,
      registrationFee: 0,
      maxRegistrations: 2000,
      prizePool: 0,
      firstPrize: "Celebrity Performance & EDM Experience",
      secondPrize: "",
      thirdPrize: "",
      scheduleStart: new Date("2026-09-08T19:30:00+05:30"),
      scheduleEnd: new Date("2026-09-08T22:30:00+05:30"),
      dayNumber: 5,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: true,
      coordinatorName: "Student Core Committee & Security Wing",
      coordinatorEmail: "astitva2026@lnjpit.ac.in",
    },

    // ------------------------------------------------------------------------
    // GAMING EVENTS
    // ------------------------------------------------------------------------
    {
      id: "evt-bgmi",
      slug: "bgmi-mobile-championship",
      title: "BGMI Mobile Championship",
      subtitle: "4-Player Squad Battle Royale",
      description: "Battlegrounds Mobile India squad tournament across Erangel, Miramar, and Sanhok maps. Live broadcasted to the big screen!",
      rules: "1. Squad of 4 (+1 optional substitute).\n2. Mobile phones only. Emulators, iPads, and triggers are banned.\n3. In-game anti-cheat and match recording verification mandatory.",
      categoryId: "cat-gaming",
      venue: "Computer Center Lab 1 & 2, LNJPIT",
      eventType: EventType.TEAM,
      minTeamSize: 4,
      maxTeamSize: 5,
      registrationFee: 0,
      maxRegistrations: 32,
      prizePool: 0,
      firstPrize: "BGMI Champions Trophy + Gold Medals + Certificates",
      secondPrize: "Runner-Up Trophy + Silver Medals + Certificates",
      thirdPrize: "Bronze Medals + Certificates",
      scheduleStart: new Date("2026-09-04T12:00:00+05:30"),
      scheduleEnd: new Date("2026-09-04T18:00:00+05:30"),
      dayNumber: 1,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: true,
      coordinatorName: "Esports Club LNJPIT",
      coordinatorEmail: "gaming@lnjpit.ac.in",
    },
    {
      id: "evt-freefire",
      slug: "free-fire-battle-arena",
      title: "Free Fire Battle Arena",
      subtitle: "High-Speed Mobile Survival Clash",
      description: "Survival of the fittest in Free Fire. Rapid zone closures, tactical squad rotations, and clutch eliminations.",
      rules: "1. Squad of 4 (+1 sub).\n2. Default competitive gun attributes enabled.\n3. Room passwords shared only with verified captain passes.",
      categoryId: "cat-gaming",
      venue: "Computer Center Lab 3, LNJPIT",
      eventType: EventType.TEAM,
      minTeamSize: 4,
      maxTeamSize: 5,
      registrationFee: 0,
      maxRegistrations: 32,
      prizePool: 0,
      firstPrize: "Free Fire Arena Champions Trophy + Medals + Certificates",
      secondPrize: "Runner-Up Trophy + Silver Medals + Certificates",
      thirdPrize: "Bronze Medals + Certificates",
      scheduleStart: new Date("2026-09-05T12:00:00+05:30"),
      scheduleEnd: new Date("2026-09-05T18:00:00+05:30"),
      dayNumber: 2,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: false,
      coordinatorName: "Esports Club LNJPIT",
      coordinatorEmail: "gaming@lnjpit.ac.in",
    },

    // ------------------------------------------------------------------------
    // LITERARY EVENTS
    // ------------------------------------------------------------------------
    {
      id: "evt-debate",
      slug: "parliamentary-debate",
      title: "National Parliamentary Debate",
      subtitle: "Bilingual Policy & Moral Debate",
      description: "Rigorous debate on national policy, technology ethics, educational reform, and socioeconomic trends.",
      rules: "1. 1-2 participants per side (Government vs Opposition).\n2. 3 minutes opening + 1 minute rebuttal + POIs allowed.\n3. Hindi & English languages supported.",
      categoryId: "cat-literary",
      venue: "Conference Hall B, Academic Block, LNJPIT",
      eventType: EventType.INDIVIDUAL,
      minTeamSize: 1,
      maxTeamSize: 2,
      registrationFee: 0,
      maxRegistrations: 40,
      prizePool: 0,
      firstPrize: "Best Orator Trophy + Gold Medal + Certificate of Excellence",
      secondPrize: "Runner-Up Trophy + Silver Medal + Certificate of Merit",
      thirdPrize: "Bronze Medal + Certificate of Commendation",
      scheduleStart: new Date("2026-09-05T10:00:00+05:30"),
      scheduleEnd: new Date("2026-09-05T14:00:00+05:30"),
      dayNumber: 2,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: false,
      coordinatorName: "Literary Society",
      coordinatorEmail: "literary@lnjpit.ac.in",
    },
    {
      id: "evt-quiz",
      slug: "mega-tech-quiz",
      title: "Mega Tech & General Quiz",
      subtitle: "Buzzer & Multimedia Trivia Arena",
      description: "General knowledge, tech trivia, science, history, current affairs, and sports pop-quiz.",
      rules: "1. Teams of 2 or 3 members.\n2. Round 1: Written prelims (30 MCQs).\n3. Round 2: Top 6 teams on stage with live buzzer and rapid-fire rounds.",
      categoryId: "cat-literary",
      venue: "Auditorium Seminar Hall B, LNJPIT",
      eventType: EventType.TEAM,
      minTeamSize: 2,
      maxTeamSize: 3,
      registrationFee: 0,
      maxRegistrations: 40,
      prizePool: 0,
      firstPrize: "Quizmaster Trophy + Gold Medals + Certificates",
      secondPrize: "Runner-Up Trophy + Silver Medals + Certificates",
      thirdPrize: "Bronze Medals + Certificates",
      scheduleStart: new Date("2026-09-06T10:00:00+05:30"),
      scheduleEnd: new Date("2026-09-06T13:00:00+05:30"),
      dayNumber: 3,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: false,
      coordinatorName: "Quiz Club LNJPIT",
      coordinatorEmail: "literary@lnjpit.ac.in",
    },
    {
      id: "evt-poetry",
      slug: "kavya-sandhya",
      title: "Kavya Sandhya (Poetry & Shayari)",
      subtitle: "Evening of Verse & Ghazals",
      description: "Self-composed Hindi, Urdu, Maithili, and English poetry recitation celebrating human emotion, society, and nature.",
      rules: "1. Original compositions only.\n2. Time limit: 4 minutes per poet.\n3. Judged on content depth, meter, rhythm, and vocal delivery.",
      categoryId: "cat-literary",
      venue: "Central Lawn Gazebo, LNJPIT",
      eventType: EventType.INDIVIDUAL,
      minTeamSize: 1,
      maxTeamSize: 1,
      registrationFee: 0,
      maxRegistrations: 40,
      prizePool: 0,
      firstPrize: "Poet Laureate Trophy + Gold Medal + Certificate",
      secondPrize: "Runner-Up Trophy + Silver Medal + Certificate",
      thirdPrize: "Bronze Medal + Certificate",
      scheduleStart: new Date("2026-09-07T16:00:00+05:30"),
      scheduleEnd: new Date("2026-09-07T19:00:00+05:30"),
      dayNumber: 4,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: false,
      coordinatorName: "Sahitya Parishad LNJPIT",
      coordinatorEmail: "literary@lnjpit.ac.in",
    },
    {
      id: "evt-creative-writing",
      slug: "creative-writing",
      title: "Creative Writing (Story & Essay)",
      subtitle: "On-the-Spot Prose Challenge",
      description: "Express your imagination, philosophical perspectives, and narrative craft through short stories and argumentative essays.",
      rules: "1. Prompts announced at the start of the event.\n2. 90 minutes writing time limit.\n3. Word count: 800–1200 words in Hindi or English.",
      categoryId: "cat-literary",
      venue: "Library Reading Hall, LNJPIT",
      eventType: EventType.INDIVIDUAL,
      minTeamSize: 1,
      maxTeamSize: 1,
      registrationFee: 0,
      maxRegistrations: 50,
      prizePool: 0,
      firstPrize: "Author of the Fest Trophy + Gold Medal + Certificate",
      secondPrize: "Runner-Up Trophy + Silver Medal + Certificate",
      thirdPrize: "Bronze Medal + Certificate",
      scheduleStart: new Date("2026-09-04T14:00:00+05:30"),
      scheduleEnd: new Date("2026-09-04T16:30:00+05:30"),
      dayNumber: 1,
      status: EventStatus.REGISTRATION_OPEN,
      isFeatured: false,
      coordinatorName: "Literary Society",
      coordinatorEmail: "literary@lnjpit.ac.in",
    },
  ];

  for (const evt of events) {
    await prisma.event.upsert({
      where: { slug: evt.slug },
      update: evt,
      create: evt,
    });
  }

  console.log(`Successfully seeded all ${events.length} official festival events into Supabase!`);
  await prisma.$disconnect();
}

main().catch((err) => {
  console.error("Failed to seed events:", err);
  process.exit(1);
});
